resources:
- manifests.yaml
- service.yaml

configurations:
- kustomizeconfig.yaml

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patches:
- patch: |-
    - op: add
      path: /webhooks/0/rules/0/scope
      value: "Namespaced"
  target:
    kind: ValidatingWebhookConfiguration
    name: validating-webhook-configuration
