---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - create
  - delete
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch.github.com
  resources:
  - immutableimages
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch.github.com
  resources:
  - immutableimages/finalizers
  verbs:
  - update
- apiGroups:
  - batch.github.com
  resources:
  - immutableimages/status
  verbs:
  - get
  - patch
  - update
