apiVersion: v1
kind: Secret
metadata:
  name: secret-1
type: Opaque
data:
  password.txt: U2VjcmV0NGV2ZXIK
  username.txt: YWRtaW4K
---
apiVersion: v1
kind: Secret
metadata:
  name: secret-2
type: Opaque
stringData:
  password.txt: Secret4EverK
  username.txt: admin
---
apiVersion: v1
kind: Secret
metadata:
  name: secret-image-not-in-cr
type: Opaque
stringData:
  access.txt: | 
    User is admin
    Password is Secret4Ever
---
apiVersion: v1
kind: Secret
metadata:
  name: secret-added-later
type: Opaque
