apiVersion: v1
kind: Pod
metadata:
  name: pod-1
spec:
  restartPolicy: Never
  volumes:
  - name: credentials
    secret:
      secretName: secret-1
  containers:
    - name: secret-container
      image: alpine:latest
      command: [ "/bin/sh", "-c", "cat /etc/foo/username.txt /etc/foo/password.txt" ]
      volumeMounts:
      - name: credentials
        mountPath: "/etc/foo"
        readOnly: true
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-2
spec:
  restartPolicy: Never
  volumes:
  - name: credentials
    secret:
      secretName: secret-2
  containers:
    - name: secret-container
      image: alpine:latest
      command: [ "/bin/sh", "-c", "cat /etc/foo/username.txt; echo; cat /etc/foo/password.txt" ]
      volumeMounts:
      - name: credentials
        mountPath: "/etc/foo"
        readOnly: true
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-image-not-in-cr
spec:
  restartPolicy: Never
  volumes:
  - name: credentials
    secret:
      secretName: secret-image-not-in-cr
  containers:
    - name: secret-container
      image: nginx:latest
      command: [ "/bin/sh", "-c", "cat /etc/foo/access.txt" ]
      volumeMounts:
      - name: credentials
        mountPath: "/etc/foo"
        readOnly: true
