---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    url: https://host.docker.internal:9443/validate--v1-secret
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUMrekNDQWVPZ0F3SUJBZ0lVYkRSOXVuK2tsU3R3emNxOFZEbXFQenRNdDlNd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0RURUxNQWtHQTFVRUJoTUNXRmd3SGhjTk1qUXhNVEkyTURJek5ESXlXaGNOTWpVeE1USTJNREl6TkRJeQpXakFOTVFzd0NRWURWUVFHRXdKWVdEQ0NBU0l3RFFZSktvWklodmNOQVFFQkJRQURnZ0VQQURDQ0FRb0NnZ0VCCkFNZ0ZidkE5bkVubVNWUUsxMnNJUU9lSlBxeVNaTW1OSGRUcGpndExNeGRtb0hyMVU3RVkrMCtBSnFBZm1GWjUKaC9rUnlGZXJiVERUZUlwYy9Ydy9vNi9JSk90bzBLejFhWG16dUhRRjZNbVovT25UWkJkSnlvcldMbmRWZHlHcQpDQ09rZnc2S0tDdnM0U1A3eUJza1pCZ0lib2dxYjIvcjNTRExvYy9QK3ZibmZJWENtODBmRURNYWZlVnJQcUpyCnorMUxLc1cvd1lIVEx4aVNOUko0YTNINlg4NWxtRVZFT2lKY0VOdnQvaUdRYWZycHdwemc3Z3ZGVHZ1cTQwdksKQ1RycjNyZlNXZmMwNkdaWVczRVlWd09DbTRjWHJxOHJhZ2tTMGtmZGd1dFdSWnRIU2hSNDhwTWJocHliRWl5WApLZ0JBcHlGaXNNTmcva1Q1b0NTWUs4MENBd0VBQWFOVE1GRXdNQVlEVlIwUkJDa3dKNElKYkc5allXeG9iM04wCmdoUm9iM04wTG1SdlkydGxjaTVwYm5SbGNtNWhiSWNFZndBQUFUQWRCZ05WSFE0RUZnUVVhS1grRldLZTVLcXMKRDZIdzlRam1JYWtmVkE4d0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFDT3hUdCtlendMdGNsdTNKQXg2WDVFeAowUHNsMUFhN3BFdnJwUmhwYzBrUU9yY0RGanBITG9DRXhBYng4cWVUMllTNHlXWHowU0JmV1BNWlVKOXA3ZHMzCnZXL0NhbFBub3pCKzBpUno0SW9QbXhBRS93RjZPYWN2VmI5eGwzekY5djhIbFFkT205RnFVZUxndXZGWkY2WVMKR3dhU2JEcThJdldXUENMem9KTVBsYzRYSFZPTFVGUGFtWEp6QnNCRlEwNlVnakFiVjhYRFkyek5QUXVmUlB4dQpkbExodGljL1o5Nk5FZkF4NkNsbk5heU9NdC9sZ2g4ZjgrbU5nbFZVdXVSL21maHZ3ZlZDTHpnbXRoc2ZDbW1TCnFwNms0ZWtqSGRzK29pWTVnanR3T1N0Q0M4SURpRGFFdFB5dHlobGtrQUVvblFsTjVtM0NJc012SExWUGtpTT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
  failurePolicy: Fail
  name: vsecret-v1.kb.io
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    # - CREATE
    - UPDATE
    resources:
    - secrets
  sideEffects: None
