apiVersion: v1
kind: Pod
metadata:
  name: pod-added-later
spec:
  restartPolicy: Never
  volumes:
  - name: credentials
    secret:
      secretName: secret-added-later
  containers:
    - name: secret-container
      image: nginx:0.3
      command: [ "/bin/sh", "-c", "cat /etc/foo/username.txt; echo; cat /etc/foo/password.txt" ]
      volumeMounts:
      - name: credentials
        mountPath: "/etc/foo"
        readOnly: true
